### ISSUE TITLE
Crossplatform with mobile?

### ISSUE THREAD

**Issue by CRiSTiK24** [CyprienGille/DnDWithin#1]
Hi! I'm looking for a DnD character sheet that I can use on mobile and PC. I can see that there is already a windows release, do you plan to bring the app to mobile and have some kind of sync between them?

If so, I'd like to help with the development. I don't know much about web development, but I have built a CI/CD pipeline for a Qt/CMake/C++ Application this summer using GitHub Actions, so I might be able to help with that as a start.

**Comment by CyprienGille** [comment]
Hello! First, thanks for your interest in DDW. 

To answer your question:

1. I do plan on bringing the app to mobile. The framework I am using, Tauri, [recently publically released the mobile feature in alpha](https://tauri.app/blog/2022/12/09/tauri-mobile-alpha). However, the mobile target is still very incomplete documentation-wise, and tedious to develop for; I will wait for the feature to be fully out before developing and releasing a mobile build! 
2. As for some kind of sync between them, I think the best course of action is to rely on the fact that both desktop and mobile versions will rely on the same `.json` files and conventions therein: thus, using a tool such as [Syncthing](https://syncthing.net/) will allow for easy, seamless and continuous syncing of the `.json` file between all devices.

I appreciate the offer for help! I don't think I need it at the moment, but I will make sure to reach out if I think I can use some of your expertise!

**Comment by CRiSTiK24** [comment]
Okay, thanks for the answer! 

I wish you the best of luck with the development, Happy new year!!!
