### ISSUE TITLE
tauri.localhost refused to connect.

### ISSUE THREAD

**Issue by KontonChowa** [CyprienGille/DnDWithin#2]
on trying to run the application im instantly told "tauri.localhost refused to connect." im unsure if this is something i have messed up on my end or if this is an application issue

**Comment by CyprienGille** [comment]
Can you try with the latest release ? (v0.2.4) 

For the record this was a mistake on my end, a wrong config parameter value.

**Comment by KontonChowa** [comment]
it works now, thanks!
